<?php

namespace app\modules\api\modules\v1\controllers;
use app\helpers\Password;
use app\models\Tokens;
use app\models\User;
use app\modules\api\filters\HeaderFilter;
use tiagocomti\cryptbox\Cryptbox;
use yii\web\BadRequestHttpException;
use yii\web\Response;
use yii\web\UnauthorizedHttpException;

class UserController extends DefaultController
{
    public function behaviors()
    {
        $behaviors = parent::behaviors();

        $behaviors['headerFilter'] = [
            'class' => HeaderFilter::class,
            'excludedActions' => [
                "security/login",
                "user/login",
                "user/health-check",
            ]
        ];
        return $behaviors; // TODO: Change the autogenerated stub
    }
    /**
     * Creating a new user for my sis. Curl example:
     */
    public function actionCreate(){
        echo "s";exit;
        return ['asd'=>true];
    }

    /**
     * @return array
     * @fluxo Recebo user:password, valido se existe user e se a senha está correta
     * se sim, retorna status code 200 e um token de acesso.
     * Caso contrário, retorno 401 para o usuário
     * @throws BadRequestHttpException
     * @throws UnauthorizedHttpException
     * @throws \SodiumException
     */
    public function actionLogin(): array
    {
        $user = User::login($this->_post["username"],$this->_post["password"]);
        if(!$user){
            throw new UnauthorizedHttpException("Login ou senha incorretos");
        }
        return ["token" => $user->getMyToken(), "type" => $user->type];
    }

    /**
     * @throws \yii\db\Exception
     * @throws UnauthorizedHttpException
     */
    public function actionHealthCheck(): bool
    {
        $token = ($this->_post["token"]);
        if(!Tokens::getUserByToken($token)){
            throw new UnauthorizedHttpException("Token não encontrado");
        }
        return true;
    }
}