<?php


namespace app\models;

use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * @SWG\Definition(required={"name"})
 * @SWG\Property(property="name", type="string")
 * @SWG\Property(property="id", type="string")
 * @SWG\Property(property="created_at", type="string")
 * @SWG\Property(property="updated_at", type="string")
 *
 * LoginForm is the model behind the login form. Preciso trocar DPO_id para user_id no coiso
 *
 * @property string $name
 * @property string $id
 * @property User[] $participantes
 */
class Equipe extends ActiveRecord
{
    /**
     * @var User
     */
    public $users;

    /**
     * @throws \yii\db\StaleObjectException
     */
    public function afterSave($insert, $changedAttributes){
        if(!$insert){
            foreach($this->users as $user_id){
                $user = User::findOne(["id" => $user_id]);
                if($user && $user->type == User::TYPE_PARTICIPANTE){
                    if($participante = Participantes::findOne(["user_id"=> $user->id])) {
                        $participante->delete();
                    }
                    $participantes = new Participantes();
                    $participantes->user_id = $user->id;
                    $participantes->equipe_id = $this->id;
                    $participantes->save();
                }
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function behaviors() {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new \yii\db\Expression('UNIX_TIMESTAMP()'),
            ]
        ];
    }

    public function rules()
    {
        return array_replace_recursive(parent::rules(),
            [
                ['name', 'unique', 'message' => 'Já tem uma equipe com esse nome'],
            ]);
    }

    public function removeParticipante(array $users_id){
        foreach ($users_id as $id) {
            $participante = Participantes::findOne(["user_id"=>$id]);
            if ($participante) {
                $participante->delete();
            }
        }
        return true;
    }

    /**
     * @return ActiveQuery
     * @throws \yii\base\InvalidConfigException
     */
    public function getParticipantes()
    {
        return $this->hasMany(strtolower(User::className()), ['id' => 'user_id'])
            ->select(["name", "email","id","username","phone"])
            ->viaTable('participantes', ['equipe_id' => 'id'],
                function (ActiveQuery $query) {
                    $query->orderBy(['id' => SORT_DESC]);
                });
    }
}